runtime: php82
service: crud-service
runtime_config:
  document_root: public
automatic_scaling:
  min_instances: 1
  max_instances: 5
  target_cpu_utilization: 0.65
resources:
  cpu: 1
  memory_gb: 2
